### ISSUE TITLE
这是 ARM 官方的那个图形库吗

### ISSUE THREAD

**Issue by SummerFalls** [yanmowudi/Synwit-Arm-2D#1]
- 这是 ARM 官方的那个图形库吗 @yanmowudi

**Comment by yanmowudi** [comment]
是的

**Comment by SummerFalls** [comment]
> 是的

想问下贵公司的 19S 和 32S 系列芯片散片目前可以购买一些自用学习吗？目前官方淘宝店铺上货不全。

**Comment by yanmowudi** [comment]
您加这个qq技术支持群492524359，在群里联系销售

**Comment by SummerFalls** [comment]
> 您加这个qq技术支持群492524359，在群里联系销售

好的 多谢。
